fix(.gh): use juju snap from 3.6/x channel
The channel 3.5/x has been removed for juju snap and install juju
from 3.5/x would result in the following error:
```
  /usr/bin/sudo snap install juju --channel=3.5/stable
  error: snap "juju" is not available on 3.5/stable but is available to install
         on the following channels:
  ...
```